# Generated by Django 5.1.11 on 2025-08-22 01:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_modelresponses"),
    ]

    operations = [
        migrations.CreateModel(
            name="videoRecordings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user", models.CharField(default="", max_length=200)),
                (
                    "recording",
                    models.FileField(upload_to="recordings/{user}/{id}.webm"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
