# Generated by Django 5.1.11 on 2025-09-02 22:25

import echocoach.myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_videorecordings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videorecordings",
            name="recording",
            field=models.FileField(
                upload_to=echocoach.myapp.models.get_video_upload_path
            ),
        ),
    ]
