# Generated by Django 5.1.11 on 2026-01-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_results"),
    ]

    operations = [
        migrations.DeleteModel(
            name="modelResponses",
        ),
        migrations.AddField(
            model_name="videorecordings",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
